// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj.command.Subsystem;
import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import com.ctre.phoenix.motorcontrol.*;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class Intake extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private WPI_TalonSRX intakeDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final static double SPEED_P_CONSTANT = 5.0;
    private final static double SPEED_I_CONSTANT = 0.0025;
    private final static double SPEED_D_CONSTANT = 0.0;
    private final static double SPEED_F_CONSTANT = 0.0;

    public double speedP = SPEED_P_CONSTANT;
    public double speedI = SPEED_I_CONSTANT;
    public double speedD = SPEED_D_CONSTANT;
    public double speedF = SPEED_F_CONSTANT;

    public final static int PID_SLOT_SPEED_MODE = 0;

    public double SHOOTER_INWARD_MULTIPLIER = 0;
    public double SHOOTER_OUTWARD_MULTIPLIER = 0;

    private final int TIMEOUT_MS = 10;
    private static final int MAX_TICKS_PER_SEC = 280;

    // need to figure out the max ticks so I just set it to 0 for now^^
    public Intake() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
intakeDrive = new WPI_TalonSRX(7);


        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new Intaking(0));

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
        intakeDrive.setNeutralMode(NeutralMode.Coast);
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
        //SmartDashboard.putNumber("Intake current speed", getTicksPerSecond());
        //SmartDashboard.putNumber("Intake desired speed", intakeDrive.get());
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void suck(double rotation) {
        this.setPercentSpeedPID(rotation);
    }

    public void initSpeedMode() {
        intakeDrive.set(ControlMode.Velocity, 0);

        intakeDrive.config_kP(PID_SLOT_SPEED_MODE, speedP, TIMEOUT_MS);
        intakeDrive.config_kI(PID_SLOT_SPEED_MODE, speedI, TIMEOUT_MS);
        intakeDrive.config_kD(PID_SLOT_SPEED_MODE, speedD, TIMEOUT_MS);
        intakeDrive.config_kF(PID_SLOT_SPEED_MODE, speedF, TIMEOUT_MS);

        intakeDrive.selectProfileSlot(PID_SLOT_SPEED_MODE, 0);
    }

    public void stop() {
        intakeDrive.set(0);
    }

    public void setPercentSpeedPID(double setSpeed) {
        intakeDrive.set(ControlMode.Velocity, MAX_TICKS_PER_SEC * setSpeed);
    }

    public int getTicksPerSecond() {
        return intakeDrive.getSelectedSensorVelocity();
    }
}
